### ISSUE TITLE
[Off topic] Which is the expanded card in the example picture?

### ISSUE THREAD

**Issue by SeanChengN** [mentalilll/ha-vpd-chart#12]
Forgive me for not using the format, I want to know what this beautiful expansion card is.
![chrome_xqF6Gz1yW8](https://github.com/user-attachments/assets/a32b5a77-917d-4f5f-be72-712951b1acb9)

**Comment by mentalilll** [comment]
Thats the default lovelace dashboard ui editor, or what exactly do you mean?

**Comment by SeanChengN** [comment]
> Thats the default lovelace dashboard ui editor, or what exactly do you mean?

Forgive my bad English, I mean it looks like an expansion card, as shown below:
![00005-1981645318-x](https://github.com/user-attachments/assets/0a6a226b-1bf2-47f9-927a-9c42eaac641c)

**Comment by mentalilll** [comment]
yes it is, its a collapsible card, i wrote it on my own, there is no home assistant default sadly for this

**Comment by SeanChengN** [comment]
> yes it is, its a collapsible card, i wrote it on my own, there is no home assistant default sadly for this

Oh! I thought it was a published card, thanks anyway!
