### ISSUE TITLE
leaf_temperature_offset of zero change the humidity and shows strange values

### ISSUE THREAD

**Issue by corgan2222** [mentalilll/ha-vpd-chart#14]
**Checklist**
- [x ] I updated the card to the latest version available
- [x ] I cleared the cache of my browser

**Describe the bug**
I was on vacation the last 3 weeks and had to update across multiple versions. After the Update, the humidity value was off by ~12% and therefore the vdp was calculated "wrong".
I created a fresh graph and had the same effect, even with different sensors.

So I tested every option and found, that `leaf_temperature_offset: 0` cause the trouble.

**Version of the card**
Version: 1.4.1

**To Reproduce**
This is the configuration I used:

add this to the config
```yaml
leaf_temperature_offset: 0
```

**Screenshots**
wrong
![grafik](https://github.com/user-attachments/assets/f59ae088-6e5b-4108-91e0-59269f637301)

correct humidity value (64,4%)
![grafik](https://github.com/user-attachments/assets/39a9692a-803b-4981-b3e8-32199b660402)

**Expected behavior**
Show the same humidity value, as give by the sensor.

**Desktop (please complete the following information):**
- chrome and firefox latest

**Comment by fuedhdf** [comment]
i have the same problem. The mobile app for iOS shows the graph correctly with  correct Hummidity value.
