### ISSUE TITLE
Can I use the VPD value to control Fans/Heating?

### ISSUE THREAD

**Issue by microfx** [mentalilll/ha-vpd-chart#16]
Hey!

Can I use the VPD value to control Fans/Heating? Would be great to make a PID with this.

Cheers!

**Comment by inZaneX** [comment]
Hey, no, its mainly to show where your stats are.
Maybe i will work on a grow plugin v2 with all that stuff, but right now, no thats not possible.

**Comment by mentalilll** [comment]
Hello, that's currently not possible.
but you could generate a feature request :).
