### ISSUE TITLE
Wrong import path when installed via HACS

### ISSUE THREAD

**Issue by jayme-github** [mentalilll/ha-vpd-chart#17]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
When installed via HACS, the `@import '/local/community/ha-vpd-chart/...` statements don't work (will give 404).
I've replaced them locally with `@import '/hacsfiles/ha-vpd-chart/...` and everything looks fine. But there is most likely a proper way to do this.

**Version of the card**
Version: 1.5.0

**To Reproduce**
Install via HACS like described in the readme, then open up the card config and see 404 errors in dev tools when fetching css files.

**Comment by inZaneX** [comment]
Hmm, thtas strange, normaly it should work without problems using local instead of hacsfiles.

i will check that

**Comment by mentalilll** [comment]
next version release will have a check for that :)
