### ISSUE TITLE
VPD Chart dot is slightly off

### ISSUE THREAD

**Issue by xandalo** [mentalilll/ha-vpd-chart#2]
**Checklist**
- [X ] I updated the card to the latest version available
- [X ] I cleared the cache of my browser

**Describe the bug**
VPD Chart is not showing the dot at the right position, it is always slightly off. 
When hovering over the chart, the dot has to be a little bit more to the left (where my mouse ist at) to be accurate for my understanding. 
Also Leaf Offset doesn't do anything for me. Or is Leaf Offset only for is_bar_view?   

**Version of the card**
Version: 1.2.0

**To Reproduce**
type: custom:ha-vpd-chart
enable_tooltip: false
enable_axes: true
enable_ghostmap: true
sensors:
  - temperature: sensor.controller_69_pro_temperature
    humidity: sensor.controller_69_pro_humidity
    name: vpd
view_layout:
  position: sidebar

**Screenshots**
![image](https://github.com/mentalilll/ha-vpd-chart/assets/167620779/5a5ded17-badc-4421-a651-87fc49752e58)

**Expected behavior**
VPD Chart point is in the correct area. 

**Desktop (please complete the following information):**
- Google Chrome

**Smartphone (please complete the following information):**
- iPhone 14 Plus
- newest iOS
- HomeAssistant App / Safari

**Additional context**

**Comment by mentalilll** [comment]
Hey nice that it works for you now :).
I will try to fix the bar view this afternoon 👍 :).

best wishes

**Comment by mentalilll** [comment]
Fixed on the newest Update. Clear Cache
