### ISSUE TITLE
VPD values are off

### ISSUE THREAD

**Issue by sekkai19** [mentalilll/ha-vpd-chart#3]
Dear devs, first of all thank you very much for your work!

I am really unsure as the VPD calculated here is significantly different from all the VPD charts that I have found.
Therefore I'd like to ask you what calculations you are using and whether the VPD estimates the Leaf VPD or the room VPD?
Upon comparing with quite some charts I havent found a single one that has the same values for combinations of temperature and humidity.

Thanks a ton!

**Comment by NoXPhasma** [comment]
By default, it applies a 2°C `leaf_temperature_offset`. If you set that to 0, it should match the VPD values of other charts. However, that option does not apply to the tooltip vpd.
